name: CorridaPlugin
main: com.corrida.inicial.starter
version: 1.0
api-version: 1.15
commands:
   inscrever:
      description: Inscreve um player na corrida!
      usage: /inscrever <Nome do player> <Nome da corrida>
   newcorrida:
      description: Cria uma nova corrida!
      usage: /newcorrida <nome_da_corrida> <Coordenadas de início> <Mundo de início> <Coordenadas de fim> <Mundo de fim> -> O mundo de início e o mundo de fim podem ser substituídos por "here" para o mundo atual do player e as coordenadas podem ser escritas como "~" para a coordenada atual do player, ou "^" para a coordenada do bloco que o player está olhando.
   addcheckpoint:
      description: Adiciona um checkpoint à corrida!
      usage: /addcheckpoint <nome_da_corrida> <Coordenadas do checkpoint> <Mundo do checkpoint> -> O mundo do checkpoint pode ser substituído por "here" para o mundo atual do player e as coordenadas podem ser escritas como "~" para a coordenada atual do player, ou "^" para a coordenada do bloco que o player está olhando.
   btc:
      description: Retorna o player ao seu último checkpoint!
      usage: /btc -> Retorna o player ao seu último checkpoint
